config/routes.rb
Rails.application.routes.draw do
  resources :tes
  resources :kihus
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kihu.rb
class Kihu < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  has_many :moves, :dependent => :destroy
  belongs_to :teban

  attr_accessor :kihu_text

  def self.parse (text)
    parsed = KihuParser.new.parse text
    result = {
      match_date: parsed[:date],
      rule: parsed[:rule],
      handicap: parsed[:handicap],
      sente: parsed[:sente],
      gote: parsed[:gote]
    }

    moves = []
    moves_num = 1
    parsed[:moves].each do |move|
      m = {
        num: moves_num,
        koma: move[:koma],
        to_x: move[:to][:x],
        to_y: move[:to][:y],
        naru: move[:naru],
        utsu: move[:utsu],
        time: move[:time]
      }
      unless m[:utsu]
        m[:from_x] = move[:from][:x]
        m[:from_y] = move[:from][:y]
      end
      moves << m
      moves_num += 1
    end

    result[:moves] = moves
    result
  end

  def self.build_with_params (params)
    moves = params[:moves]
    kihu = Kihu.new params.except :moves
    moves.each do |move|
      kihu.moves.build move
    end
    kihu
  end

end

app/models/koma_type.rb
class KomaType < ActiveHash::Base
  self.data = [
    {:id => 1, :name => 'hu'},
    {:id => 2, :name => 'keima'},
    {:id => 3, :name => 'kyousya'},
    {:id => 4, :name => 'gin'},
    {:id => 5, :name => 'kin'},
    {:id => 6, :name => 'ou'},
    {:id => 7, :name => 'hisya'},
    {:id => 8, :name => 'kaku'},
    {:id => 9, :name => 'to'},
    {:id => 10, :name => 'nari_kei'},
    {:id => 11, :name => 'nari_kyou'},
    {:id => 12, :name => 'nari_gin'},
    {:id => 13, :name => 'ryuu'},
    {:id => 14, :name => 'uma'},
  ]

  def self.get_by_name (name)
    target = nil
    data.each {|kt| target = kt if kt[:name] == name}
    target
  end
end

app/models/move.rb
class Move < ApplicationRecord
end

app/models/teban.rb
class Teban < ActiveHash::Base
  self.data = [
    {:id => 1, :name => 'sente', :label => '先手'},
    {:id => 2, :name => 'gote', :label => '後手'}
  ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kihus_controller.rb
class KihusController < ApplicationController
  before_action :set_kihu, only: [:show, :edit, :update, :destroy]

  # GET /kihus
  # GET /kihus.json
  def index
    @kihus = Kihu.all
  end

  # GET /kihus/1
  # GET /kihus/1.json
  def show
    gon.moves = @kihu.moves
  end

  # GET /kihus/new
  def new
    @kihu = Kihu.new
  end

  # GET /kihus/1/edit
  def edit
  end

  # POST /kihus
  # POST /kihus.json
  def create

    @kihu = Kihu.build_with_params kihu_params

    respond_to do |format|
      if @kihu.save
        format.html { redirect_to @kihu, notice: 'Kihu was successfully created.' }
        format.json { render :show, status: :created, location: @kihu }
      else
        format.html { render :new }
        format.json { render json: @kihu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kihus/1
  # PATCH/PUT /kihus/1.json
  def update
    respond_to do |format|
      if @kihu.update(kihu_params)
        format.html { redirect_to @kihu, notice: 'Kihu was successfully updated.' }
        format.json { render :show, status: :ok, location: @kihu }
      else
        format.html { render :edit }
        format.json { render json: @kihu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kihus/1
  # DELETE /kihus/1.json
  def destroy
    @kihu.destroy
    respond_to do |format|
      format.html { redirect_to kihus_url, notice: 'Kihu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kihu
      @kihu = Kihu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kihu_params
      _params = params.require(:kihu).permit(:teban_id, :won, :kihu_text).to_h
      if _params[:kihu_text]
        _params.merge! Kihu.parse _params[:kihu_text]
        _params.delete :kihu_text
      end
      _params
    end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :set_move, only: [:show, :edit, :update, :destroy]

  # GET /moves
  # GET /moves.json
  def index
    @moves = Move.all
  end

  # GET /moves/1
  # GET /moves/1.json
  def show
  end

  # GET /moves/new
  def new
    @move = Move.new
  end

  # GET /moves/1/edit
  def edit
  end

  # POST /moves
  # POST /moves.json
  def create
    @move = Move.new(move_params)

    respond_to do |format|
      if @move.save
        format.html { redirect_to @move, notice: 'Move was successfully created.' }
        format.json { render :show, status: :created, location: @move }
      else
        format.html { render :new }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moves/1
  # PATCH/PUT /moves/1.json
  def update
    respond_to do |format|
      if @move.update(move_params)
        format.html { redirect_to @move, notice: 'Move was successfully updated.' }
        format.json { render :show, status: :ok, location: @move }
      else
        format.html { render :edit }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moves/1
  # DELETE /moves/1.json
  def destroy
    @move.destroy
    respond_to do |format|
      format.html { redirect_to moves_url, notice: 'Move was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_move
      @move = Move.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def move_params
      params.require(:move).permit(:content, :comment, :kihu)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kihus/_form.html.erb
<%= form_for @kihu, :html => { :class => "form-horizontal kihu" } do |f| %>

  <% if @kihu.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@kihu.errors.count, "error") %> prohibited this kihu from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @kihu.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :teban, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.collection_select :teban_id, Teban.all, :id, :label, :class => 'form-control' %>
    </div>
    <%=f.error_span(:teban) %>
  </div>
  <div class="form-group">
    <%= f.label :won, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.check_box :won, :class => 'form-control' %>
    </div>
    <%=f.error_span(:won) %>
  </div>
  <div class="form-group">
    <%= f.label '棋譜', :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :kihu_text, :class => 'form-control' %>
    </div>
    <%=f.error_span(:match_date) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                kihus_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/kihus/edit.html.erb
<%- model_class = Kihu -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/kihus/index.html.erb
<%- model_class = Kihu -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:teban) %></th>
      <th><%= model_class.human_attribute_name(:won) %></th>
      <th><%= model_class.human_attribute_name(:match_date) %></th>
      <th><%= model_class.human_attribute_name(:rule) %></th>
      <th><%= model_class.human_attribute_name(:handicap) %></th>
      <th><%= model_class.human_attribute_name(:sente) %></th>
      <th><%= model_class.human_attribute_name(:gote) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @kihus.each do |kihu| %>
      <tr>
        <td><%= link_to kihu.id, kihu_path(kihu) %></td>
        <td><%= kihu.teban.label %></td>
        <td><%= kihu.won %></td>
        <td><%= kihu.match_date %></td>
        <td><%= kihu.rule %></td>
        <td><%= kihu.handicap %></td>
        <td><%= kihu.sente %></td>
        <td><%= kihu.gote %></td>
        <td><%=l kihu.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_kihu_path(kihu), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      kihu_path(kihu),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_kihu_path,
            :class => 'btn btn-primary' %>

app/views/kihus/new.html.erb
<%- model_class = Kihu -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/kihus/show.html.erb
<%- model_class = Kihu -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class='row'>
  <div class='col-sm-5'>
    <dl class="dl-horizontal">
      <dt><strong><%= model_class.human_attribute_name(:teban) %>:</strong></dt>
      <dd><%= @kihu.teban.label %></dd>
      <dt><strong><%= model_class.human_attribute_name(:won) %>:</strong></dt>
      <dd><%= @kihu.won %></dd>
      <dt><strong><%= model_class.human_attribute_name(:match_date) %>:</strong></dt>
      <dd><%= @kihu.match_date %></dd>
      <dt><strong><%= model_class.human_attribute_name(:rule) %>:</strong></dt>
      <dd><%= @kihu.rule %></dd>
      <dt><strong><%= model_class.human_attribute_name(:handicap) %>:</strong></dt>
      <dd><%= @kihu.handicap %></dd>
      <dt><strong><%= model_class.human_attribute_name(:sente) %>:</strong></dt>
      <dd><%= @kihu.sente %></dd>
      <dt><strong><%= model_class.human_attribute_name(:gote) %>:</strong></dt>
      <dd><%= @kihu.gote %></dd>
    </dl>

    <%= link_to t('.back', :default => t("helpers.links.back")),
                  kihus_path, :class => 'btn btn-default'  %>
    <%= link_to t('.edit', :default => t("helpers.links.edit")),
                  edit_kihu_path(@kihu), :class => 'btn btn-default' %>
    <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                  kihu_path(@kihu),
                  :method => 'delete',
                  :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                  :class => 'btn btn-danger' %>
  </div>

  <div class='col-sm-7'>
    <div id='moves-container'></div>
  </div>
</div>

<%= javascript_include_tag 'webpack/vendor.bundle' %>
<%= javascript_include_tag 'webpack/kihus/show.bundle' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Server</title>
    <%= csrf_meta_tags %>
    <%= include_gon %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/moves/_form.html.erb
<%= form_for(te) do |f| %>
  <% if te.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(te.errors.count, "error") %> prohibited this te from being saved:</h2>

      <ul>
      <% te.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <div class="field">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="field">
    <%= f.label :kihu %>
    <%= f.text_field :kihu %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/moves/edit.html.erb
<h1>Editing Te</h1>

<%= render 'form', te: @te %>

<%= link_to 'Show', @te %> |
<%= link_to 'Back', tes_path %>

app/views/moves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tes</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Comment</th>
      <th>Kihu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tes.each do |te| %>
      <tr>
        <td><%= te.content %></td>
        <td><%= te.comment %></td>
        <td><%= te.kihu %></td>
        <td><%= link_to 'Show', te %></td>
        <td><%= link_to 'Edit', edit_te_path(te) %></td>
        <td><%= link_to 'Destroy', te, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Te', new_te_path %>

app/views/moves/new.html.erb
<h1>New Te</h1>

<%= render 'form', te: @te %>

<%= link_to 'Back', tes_path %>

app/views/moves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @te.content %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @te.comment %>
</p>

<p>
  <strong>Kihu:</strong>
  <%= @te.kihu %>
</p>

<%= link_to 'Edit', edit_te_path(@te) %> |
<%= link_to 'Back', tes_path %>